ALTER TABLE work_items ADD COLUMN autocontinue INTEGER NOT NULL DEFAULT 1;
ALTER TABLE work_items ADD COLUMN continues_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE work_items ADD COLUMN continue_cap INTEGER NOT NULL DEFAULT 5;
