[instances]

[[instances.list]]
key = "aimyable"
base_url = "https://aimyable.frshty.localhost"
platform = "bitbucket"
ticket_system = "jira"

[[instances.list]]
key = "atropos"
base_url = "http://192.168.1.117:7100"
platform = "github"
ticket_system = "jira"

[[instances.list]]
key = "nectar"
base_url = "https://nectar.frshty.localhost"
platform = "github"
ticket_system = "linear"

[[instances.list]]
key = "lumeninv"
base_url = "https://lumeninv.frshty.localhost"
platform = "github"
ticket_system = "prd"

[[instances.list]]
key = "bh"
base_url = "https://bh.frshty.localhost"
platform = "github"
ticket_system = "prd"

